-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME
        WHERE HOUR < 23
)

SELECT HOUR, COUNT(HOUR)-1 AS COUNT
FROM (
    SELECT HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
    UNION ALL
    SELECT HOUR
    FROM TIME
) UN
GROUP BY HOUR
ORDER BY HOUR